#!/usr/bin/env python3
"""
Flag icons and layout mappings for keyboard panel
"""

# Unicode flag emoji mappings for layouts
LAYOUT_FLAGS = {
    'us': '🇺🇸',
    'en': '🇺🇸',
    'ru': '🇷🇺',
    'de': '🇩🇪',
    'fr': '🇫🇷',
    'es': '🇪🇸',
    'it': '🇮🇹',
    'pt': '🇵🇹',
    'br': '🇧🇷',
    'nl': '🇳🇱',
    'pl': '🇵🇱',
    'cz': '🇨🇿',
    'sk': '🇸🇰',
    'hu': '🇭🇺',
    'fi': '🇫🇮',
    'se': '🇸🇪',
    'no': '🇳🇴',
    'dk': '🇩🇰',
    'is': '🇮🇸',
    'gr': '🇬🇷',
    'tr': '🇹🇷',
    'ua': '🇺🇦',
    'by': '🇧🇾',
    'bg': '🇧🇬',
    'hr': '🇭🇷',
    'rs': '🇷🇸',
    'si': '🇸🇮',
    'mk': '🇲🇰',
    'al': '🇦🇱',
    'ro': '🇷🇴',
    'md': '🇲🇩',
    'lt': '🇱🇹',
    'lv': '🇱🇻',
    'ee': '🇪🇪',
    'jp': '🇯🇵',
    'kr': '🇰🇷',
    'cn': '🇨🇳',
    'tw': '🇹🇼',
    'hk': '🇭🇰',
    'in': '🇮🇳',
    'th': '🇹🇭',
    'vn': '🇻🇳',
    'id': '🇮🇩',
    'my': '🇲🇾',
    'ph': '🇵🇭',
    'sg': '🇸🇬',
    'ar': '🇸🇦',
    'ae': '🇦🇪',
    'il': '🇮🇱',
    'ir': '🇮🇷',
    'pk': '🇵🇰',
    'bd': '🇧🇩',
    'lk': '🇱🇰',
    'np': '🇳🇵',
    'mm': '🇲🇲',
    'kh': '🇰🇭',
    'la': '🇱🇦',
    'mn': '🇲🇳',
    'kz': '🇰🇿',
    'uz': '🇺🇿',
    'kg': '🇰🇬',
    'tj': '🇹🇯',
    'tm': '🇹🇲',
    'af': '🇦🇫',
    'am': '🇦🇲',
    'az': '🇦🇿',
    'ge': '🇬🇪'
}

# ASCII art flags for terminals without emoji support
ASCII_FLAGS = {
    'us': 'US',
    'en': 'EN',
    'ru': 'RU',
    'de': 'DE',
    'fr': 'FR',
    'es': 'ES',
    'it': 'IT',
    'pt': 'PT',
    'br': 'BR',
    'nl': 'NL',
    'pl': 'PL',
    'cz': 'CZ',
    'sk': 'SK',
    'hu': 'HU',
    'fi': 'FI',
    'se': 'SE',
    'no': 'NO',
    'dk': 'DK',
    'is': 'IS',
    'gr': 'GR',
    'tr': 'TR',
    'ua': 'UA',
    'by': 'BY',
    'bg': 'BG',
    'hr': 'HR',
    'rs': 'RS',
    'si': 'SI',
    'mk': 'MK',
    'al': 'AL',
    'ro': 'RO',
    'md': 'MD',
    'lt': 'LT',
    'lv': 'LV',
    'ee': 'EE',
    'jp': 'JP',
    'kr': 'KR',
    'cn': 'CN',
    'tw': 'TW',
    'hk': 'HK',
    'in': 'IN',
    'th': 'TH',
    'vn': 'VN',
    'id': 'ID',
    'my': 'MY',
    'ph': 'PH',
    'sg': 'SG',
    'ar': 'AR',
    'ae': 'AE',
    'il': 'IL',
    'ir': 'IR',
    'pk': 'PK',
    'bd': 'BD',
    'lk': 'LK',
    'np': 'NP',
    'mm': 'MM',
    'kh': 'KH',
    'la': 'LA',
    'mn': 'MN',
    'kz': 'KZ',
    'uz': 'UZ',
    'kg': 'KG',
    'tj': 'TJ',
    'tm': 'TM',
    'af': 'AF',
    'am': 'AM',
    'az': 'AZ',
    'ge': 'GE'
}

def get_flag_emoji(layout):
    """Get flag emoji for layout"""
    return LAYOUT_FLAGS.get(layout.lower(), '🏁')

def get_flag_text(layout):
    """Get flag text representation for layout"""
    return ASCII_FLAGS.get(layout.lower(), layout.upper())

def get_country_name(layout):
    """Get country name for layout"""
    country_names = {
        'us': 'United States',
        'en': 'English',
        'ru': 'Russia',
        'de': 'Germany',
        'fr': 'France',
        'es': 'Spain',
        'it': 'Italy',
        'pt': 'Portugal',
        'br': 'Brazil',
        'nl': 'Netherlands',
        'pl': 'Poland',
        'cz': 'Czech Republic',
        'sk': 'Slovakia',
        'hu': 'Hungary',
        'fi': 'Finland',
        'se': 'Sweden',
        'no': 'Norway',
        'dk': 'Denmark',
        'is': 'Iceland',
        'gr': 'Greece',
        'tr': 'Turkey',
        'ua': 'Ukraine',
        'by': 'Belarus',
        'bg': 'Bulgaria',
        'hr': 'Croatia',
        'rs': 'Serbia',
        'si': 'Slovenia',
        'mk': 'Macedonia',
        'al': 'Albania',
        'ro': 'Romania',
        'md': 'Moldova',
        'lt': 'Lithuania',
        'lv': 'Latvia',
        'ee': 'Estonia',
        'jp': 'Japan',
        'kr': 'South Korea',
        'cn': 'China',
        'tw': 'Taiwan',
        'hk': 'Hong Kong',
        'in': 'India',
        'th': 'Thailand',
        'vn': 'Vietnam',
        'id': 'Indonesia',
        'my': 'Malaysia',
        'ph': 'Philippines',
        'sg': 'Singapore',
        'ar': 'Arabic',
        'ae': 'UAE',
        'il': 'Israel',
        'ir': 'Iran',
        'pk': 'Pakistan',
        'bd': 'Bangladesh',
        'lk': 'Sri Lanka',
        'np': 'Nepal',
        'mm': 'Myanmar',
        'kh': 'Cambodia',
        'la': 'Laos',
        'mn': 'Mongolia',
        'kz': 'Kazakhstan',
        'uz': 'Uzbekistan',
        'kg': 'Kyrgyzstan',
        'tj': 'Tajikistan',
        'tm': 'Turkmenistan',
        'af': 'Afghanistan',
        'am': 'Armenia',
        'az': 'Azerbaijan',
        'ge': 'Georgia'
    }
    return country_names.get(layout.lower(), layout.upper())